### ISSUE TITLE
Hello, do you have any related comprehensive survey/overview papers? If so, thank you very much.

### ISSUE THREAD

**Issue by YuanduLai** [ahmedmalaa/uncertainty-quantification-deep-learning#2]
Hello, I am studying uncertainty estimation recently, I need a survey/overview paper, can you help me? Thank you very much.

**Comment by ahmedmalaa** [comment]
Hi YuanduLai,

Unfortunately I am not aware of any such survey, but will post if I find any.


Best regards.
